
CREATE TABLE UserSearch (
    srch_id BIGINT,
    date_time TIMESTAMP WITH TIME ZONE,
    site_id BIGINT,
    visitor_location_country_id BIGINT,
    visitor_hist_starrating DOUBLE PRECISION,
    visitor_hist_adr_usd DOUBLE PRECISION,
    prop_country_id BIGINT,
    prop_id BIGINT,
    prop_starrating BIGINT,
    prop_review_score DOUBLE PRECISION,
    prop_brand_bool BIGINT,
    prop_location_score1 DOUBLE PRECISION,
    prop_location_score2 DOUBLE PRECISION,
    prop_log_historical_price DOUBLE PRECISION,
    position BIGINT,
    price_usd DOUBLE PRECISION,
    promotion_flag BIGINT,
    srch_destination_id BIGINT,
    srch_length_of_stay BIGINT,
    srch_booking_window BIGINT,
    srch_adults_count BIGINT,
    srch_children_count BIGINT,
    srch_room_count BIGINT,
    srch_saturday_night_bool BIGINT,
    srch_query_affinity_score DOUBLE PRECISION,
    orig_destination_distance DOUBLE PRECISION,
    random_bool BIGINT,
    comp1_rate DOUBLE PRECISION,
    comp1_inv DOUBLE PRECISION,
    comp1_rate_percent_diff DOUBLE PRECISION,
    comp2_rate DOUBLE PRECISION,
    comp2_inv DOUBLE PRECISION,
    comp2_rate_percent_diff DOUBLE PRECISION,
    comp3_rate DOUBLE PRECISION,
    comp3_inv DOUBLE PRECISION,
    comp3_rate_percent_diff DOUBLE PRECISION,
    comp4_rate DOUBLE PRECISION,
    comp4_inv DOUBLE PRECISION,
    comp4_rate_percent_diff DOUBLE PRECISION,
    comp5_rate DOUBLE PRECISION,
    comp5_inv DOUBLE PRECISION,
    comp5_rate_percent_diff DOUBLE PRECISION,
    comp6_rate DOUBLE PRECISION,
    comp6_inv DOUBLE PRECISION,
    comp6_rate_percent_diff DOUBLE PRECISION,
    comp7_rate DOUBLE PRECISION,
    comp7_inv DOUBLE PRECISION,
    comp7_rate_percent_diff DOUBLE PRECISION,
    comp8_rate DOUBLE PRECISION,
    comp8_inv DOUBLE PRECISION,
    comp8_rate_percent_diff DOUBLE PRECISION,
    click_bool BIGINT,
    gross_bookings_usd DOUBLE PRECISION,
    booking_bool BIGINT);

COPY UserSearch FROM 'C:\Users\ben_000\Dropbox\Data\ExpediaPersonalizedSort\Raw\ExpediaRaw.tsv' DELIMITERS '(tab goes here)' CSV HEADER NULL AS 'NULL';